name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pandas

      - name: Build executable
        run: |
          pyinstaller --onefile --noconsole --distpath dist Excel-SQLite_converter.py
          
      - name: List directory contents
        run: dir dist || echo "No dist directory found"

      - name: Upload executable
        if: success() && steps.build.outcome == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: app-executable
          path: dist/Excel-SQLite_converter.exe
